version: '3.9'

services:
  service-db-redis:
    restart: always
    image: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro

  service-db-postgres:
    restart: always
    image: postgres:14
    volumes:
      - ../db/migrations/db_schema.sql:/docker-entrypoint-initdb.d/migration_1.sql
      - ../db/fill_data/data_filling.sql:/docker-entrypoint-initdb.d/migration_2.sql
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  service-minio:
    restart: always
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data

  create_buckets:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set musicon http://service-minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb --ignore-existing musicon/user-avatar;
      /usr/bin/mc mb --ignore-existing musicon/playlist-image;
      /usr/bin/mc anonymous set download musicon/user-avatar;
      /usr/bin/mc anonymous set download musicon/playlist-image;
      exit 0;
      "