version: '3.9'

services:
  service-minio:
    image: minio/minio
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data


  create_buckets:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set musicon http://localhost:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb --ignore-existing musicon/user-avatar;
      /usr/bin/mc mb --ignore-existing musicon/playlist-image;
      /usr/bin/mc anonymous set download musicon/user-avatar;
      /usr/bin/mc anonymous set download musicon/playlist-image;
      exit 0;
      "
