---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: musicon
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: kafka
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: musicon
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
      namespace: musicon
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:6.2.1
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
              name: kafka-port
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-service
#spec:
#  selector:
#    app: kafka
#  ports:
#    - protocol: TCP
#      port: 9092
#      targetPort: 9092
#
#---
#
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: kafka-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: kafka
#  template:
#    metadata:
#      labels:
#        app: kafka
#    spec:
#      containers:
#        - name: kafka
#          image: confluentinc/cp-kafka:6.2.1
#          ports:
#            - containerPort: 9092
#          env:
#            - name: KAFKA_ADVERTISED_HOST_NAME
#              value: kafka
#            - name: KAFKA_ADVERTISED_PORT
#              value: "9092"
#            - name: KAFKA_ADVERTISED_LISTENERS
#              value: "PLAINTEXT://kafka:9092"
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: "zookeeper:2181"
#            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
#              value: "true"
#            - name: KAFKA_DELETE_TOPIC_ENABLE
#              value: "true"
