---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
  namespace: musicon
spec:
  clusterIP: None
  ports:
    - port: 2181
      name: zookeeper
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: musicon
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
      namespace: musicon
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:6.2.1
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
              name: zookeeper-port
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
#
#
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: zookeeper-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: zookeeper
#  template:
#    metadata:
#      labels:
#        app: zookeeper
#    spec:
#      containers:
#        - name: zookeeper
#          image: confluentinc/cp-zookeeper:6.2.1
#          ports:
#            - containerPort: 2181
