services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT=8080

  service-db:
    image: postgres:16
    environment:
      POSTGRES_DB: "musicon"
      POSTGRES_USER: "musicon"
      POSTGRES_PASSWORD: "musicon"
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

#  proxy:
#    image: nginx
#    volumes:
#      - type: bind
#        source: ./proxy/nginx.conf
 #       target: /etc/nginx/conf.d/default.conf
  #      read_only: true
  #  ports:
  #    - 8000:8000
  #  depends_on:
  #    - backend

volumes:
  db-data:
