version: '3.0'

services:
  
  service-db:
    restart: always
    image: postgres:14
    env_file: ./database/db.env
    ports:
      - "${P0STGRES_PORT}:${P0STGRES_PORT}"
    volumes:
      - ./database/db_schema.sql:/db_schema.sql
      - ./database/startup.sh:/docker-entrypoint-initdb.d/startup.sh
      - ./db-data:/var/lib/postgresql/data
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - service-db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: ./database/db.env
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - P0STGRES_PORT=${P0STGRES_PORT}

#  proxy:
#    image: nginx
#    volumes:
#      - type: bind
#        source: ./proxy/nginx.conf
 #       target: /etc/nginx/conf.d/default.conf
  #      read_only: true
  #  ports:
  #    - 8000:8000
  #  depends_on:
  #    - backend
