version: '3.7'

services:
  service-db-redis:
    restart: always
    image: redis
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  service-db-postgres:
    restart: always
    image: postgres:14
    env_file: ./database/db.env
    network_mode: host
    volumes:
      - ./database/migrations/migration_1.sql:/docker-entrypoint-initdb.d/migration_1.sql
      - ./database/migrations/migration_2.sql:/docker-entrypoint-initdb.d/migration_2.sql
      - ~/db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U musicon" ]
      interval: 10s
      retries: 3
      timeout: 5s

  musicon:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      service-db-postgres:
        condition: service_healthy
      service-db-redis:
        condition: service_healthy
    network_mode: host
    environment:
      - DATABASE_URL=postgres://musicon:musicon@localhost:5432/musicon
      - /etc/localtime:/etc/localtime:ro

  wait-musicon:
    image: alpine
    depends_on:
      - musicon
    command: >
      /bin/sh -c "apk add --no-cache curl && 
                  while true; do
                    if curl -s -o /dev/null http://musicon:8080; then
                      break;
                    fi;
                    sleep 1;
                  done;"
