version: '3.0'

services:
  
  service-db:
    restart: always
    image: postgres:14
    env_file: ./database/db.env
    ports:
      - "5432:5432"
    volumes:
      - ./database/db_schema.sql:/db_schema.sql
      - ./database/startup.sh:/docker-entrypoint-initdb.d/startup.sh
      - ./db-data:/var/lib/postgresql/data
    networks:
      staic-network:
        ipv4_address: 172.28.1.101
      
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - service-db
    ports:
      - "8080:8080"
    env_file: ./database/db.env
    networks:
      - staic-network

networks:
  staic-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.1.0/24


