version: '3.7'

services:
  service-minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ~/minio:/data
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    
  create_buckets:
    image: minio/mc
    depends_on:
      service-minio:
        condition: service_healthy
    network_mode: host
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set musicon http://localhost:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb --ignore-existing musicon/user-avatar;
      /usr/bin/mc mb --ignore-existing musicon/playlist-image;
      /usr/bin/mc anonymous set download musicon/user-avatar;
      /usr/bin/mc anonymous set download musicon/playlist-image;
      exit 0;
      "
