// Code generated by protoc-gen-go. DO NOT EDIT.
// source: onboarding.proto

package onboarding

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	proto1 "main/internal/microservices/artist/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenreBase struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Preview              string   `protobuf:"bytes,3,opt,name=Preview,proto3" json:"Preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenreBase) Reset()         { *m = GenreBase{} }
func (m *GenreBase) String() string { return proto.CompactTextString(m) }
func (*GenreBase) ProtoMessage()    {}
func (*GenreBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_afe1fceb30c27431, []int{0}
}

func (m *GenreBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenreBase.Unmarshal(m, b)
}
func (m *GenreBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenreBase.Marshal(b, m, deterministic)
}
func (m *GenreBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenreBase.Merge(m, src)
}
func (m *GenreBase) XXX_Size() int {
	return xxx_messageInfo_GenreBase.Size(m)
}
func (m *GenreBase) XXX_DiscardUnknown() {
	xxx_messageInfo_GenreBase.DiscardUnknown(m)
}

var xxx_messageInfo_GenreBase proto.InternalMessageInfo

func (m *GenreBase) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GenreBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GenreBase) GetPreview() string {
	if m != nil {
		return m.Preview
	}
	return ""
}

type GenresBase struct {
	Genres               []*GenreBase `protobuf:"bytes,1,rep,name=Genres,proto3" json:"Genres,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenresBase) Reset()         { *m = GenresBase{} }
func (m *GenresBase) String() string { return proto.CompactTextString(m) }
func (*GenresBase) ProtoMessage()    {}
func (*GenresBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_afe1fceb30c27431, []int{1}
}

func (m *GenresBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenresBase.Unmarshal(m, b)
}
func (m *GenresBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenresBase.Marshal(b, m, deterministic)
}
func (m *GenresBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenresBase.Merge(m, src)
}
func (m *GenresBase) XXX_Size() int {
	return xxx_messageInfo_GenresBase.Size(m)
}
func (m *GenresBase) XXX_DiscardUnknown() {
	xxx_messageInfo_GenresBase.DiscardUnknown(m)
}

var xxx_messageInfo_GenresBase proto.InternalMessageInfo

func (m *GenresBase) GetGenres() []*GenreBase {
	if m != nil {
		return m.Genres
	}
	return nil
}

type GenreOnboarding struct {
	Genres               *GenresBase `protobuf:"bytes,1,opt,name=Genres,proto3" json:"Genres,omitempty"`
	UserId               string      `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenreOnboarding) Reset()         { *m = GenreOnboarding{} }
func (m *GenreOnboarding) String() string { return proto.CompactTextString(m) }
func (*GenreOnboarding) ProtoMessage()    {}
func (*GenreOnboarding) Descriptor() ([]byte, []int) {
	return fileDescriptor_afe1fceb30c27431, []int{2}
}

func (m *GenreOnboarding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenreOnboarding.Unmarshal(m, b)
}
func (m *GenreOnboarding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenreOnboarding.Marshal(b, m, deterministic)
}
func (m *GenreOnboarding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenreOnboarding.Merge(m, src)
}
func (m *GenreOnboarding) XXX_Size() int {
	return xxx_messageInfo_GenreOnboarding.Size(m)
}
func (m *GenreOnboarding) XXX_DiscardUnknown() {
	xxx_messageInfo_GenreOnboarding.DiscardUnknown(m)
}

var xxx_messageInfo_GenreOnboarding proto.InternalMessageInfo

func (m *GenreOnboarding) GetGenres() *GenresBase {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *GenreOnboarding) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ArtistOnboarding struct {
	Artists              *proto1.ArtistsBase `protobuf:"bytes,1,opt,name=Artists,proto3" json:"Artists,omitempty"`
	UserId               string              `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ArtistOnboarding) Reset()         { *m = ArtistOnboarding{} }
func (m *ArtistOnboarding) String() string { return proto.CompactTextString(m) }
func (*ArtistOnboarding) ProtoMessage()    {}
func (*ArtistOnboarding) Descriptor() ([]byte, []int) {
	return fileDescriptor_afe1fceb30c27431, []int{3}
}

func (m *ArtistOnboarding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtistOnboarding.Unmarshal(m, b)
}
func (m *ArtistOnboarding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtistOnboarding.Marshal(b, m, deterministic)
}
func (m *ArtistOnboarding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtistOnboarding.Merge(m, src)
}
func (m *ArtistOnboarding) XXX_Size() int {
	return xxx_messageInfo_ArtistOnboarding.Size(m)
}
func (m *ArtistOnboarding) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtistOnboarding.DiscardUnknown(m)
}

var xxx_messageInfo_ArtistOnboarding proto.InternalMessageInfo

func (m *ArtistOnboarding) GetArtists() *proto1.ArtistsBase {
	if m != nil {
		return m.Artists
	}
	return nil
}

func (m *ArtistOnboarding) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*GenreBase)(nil), "GenreBase")
	proto.RegisterType((*GenresBase)(nil), "GenresBase")
	proto.RegisterType((*GenreOnboarding)(nil), "GenreOnboarding")
	proto.RegisterType((*ArtistOnboarding)(nil), "ArtistOnboarding")
}

func init() {
	proto.RegisterFile("onboarding.proto", fileDescriptor_afe1fceb30c27431)
}

var fileDescriptor_afe1fceb30c27431 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x97, 0x6d, 0x6c, 0xec, 0x75, 0xea, 0x96, 0x83, 0x94, 0x79, 0x19, 0x11, 0xa4, 0xa7,
	0x4c, 0xaa, 0x07, 0xf1, 0xe6, 0x40, 0xa4, 0x97, 0x29, 0x1d, 0x5e, 0xbc, 0x75, 0xf6, 0x59, 0x0a,
	0xae, 0x19, 0x69, 0xac, 0xf8, 0x77, 0xfb, 0x0f, 0x48, 0xd3, 0xa4, 0xad, 0x83, 0xde, 0xf2, 0xe5,
	0xf5, 0xfb, 0xe5, 0x7d, 0x1f, 0x85, 0x99, 0xc8, 0x76, 0x22, 0x92, 0x71, 0x9a, 0x25, 0xfc, 0x20,
	0x85, 0x12, 0x8b, 0x69, 0x24, 0x55, 0x9a, 0x2b, 0xa3, 0x2e, 0x12, 0x21, 0x92, 0x4f, 0x5c, 0x69,
	0xb5, 0xfb, 0xfa, 0x58, 0xe1, 0xfe, 0xa0, 0x7e, 0xaa, 0x21, 0x0b, 0x60, 0xf2, 0x84, 0x99, 0xc4,
	0x75, 0x94, 0x23, 0x3d, 0x85, 0x7e, 0x10, 0xbb, 0x64, 0x49, 0xbc, 0x61, 0xd8, 0x0f, 0x62, 0x4a,
	0x61, 0xb8, 0x89, 0xf6, 0xe8, 0xf6, 0x97, 0xc4, 0x9b, 0x84, 0xfa, 0x4c, 0x5d, 0x18, 0xbf, 0x48,
	0x2c, 0x52, 0xfc, 0x76, 0x07, 0xfa, 0xda, 0x4a, 0x76, 0x0d, 0xa0, 0x51, 0xb9, 0x66, 0x31, 0x18,
	0x55, 0xca, 0x25, 0xcb, 0x81, 0xe7, 0xf8, 0xc0, 0xeb, 0x77, 0x42, 0x33, 0x61, 0x1b, 0x38, 0xd3,
	0xa7, 0xe7, 0x3a, 0x00, 0xbd, 0x6c, 0xd9, 0x88, 0xe7, 0xf8, 0x0e, 0x6f, 0x98, 0xd6, 0x47, 0xcf,
	0x61, 0xf4, 0x9a, 0xa3, 0x0c, 0x62, 0xb3, 0x99, 0x51, 0x2c, 0x84, 0xd9, 0x83, 0x4e, 0xde, 0x02,
	0x5e, 0xc1, 0xb8, 0xba, 0xb3, 0xc4, 0x29, 0x37, 0x5a, 0x23, 0xed, 0xb0, 0x8b, 0xe9, 0xff, 0x12,
	0x98, 0x37, 0xb8, 0x2d, 0xca, 0x22, 0x7d, 0x47, 0x7a, 0x5b, 0x66, 0x55, 0xb5, 0x97, 0x57, 0x15,
	0x73, 0x5b, 0x31, 0x7f, 0x2c, 0x2b, 0x5e, 0xfc, 0x7b, 0x8a, 0xf5, 0xa8, 0x5f, 0x96, 0xad, 0x6c,
	0x88, 0x0e, 0x53, 0x3b, 0x31, 0xeb, 0xd1, 0x3b, 0x80, 0x6d, 0x54, 0xa0, 0x31, 0xcd, 0xf8, 0x51,
	0x61, 0x8b, 0x0e, 0x0c, 0xeb, 0xd1, 0x7b, 0x70, 0x4a, 0xa7, 0x5d, 0x72, 0xce, 0x8f, 0xbb, 0xe9,
	0xf6, 0xae, 0x4f, 0xde, 0x9c, 0x55, 0xf3, 0x5b, 0xed, 0x46, 0xfa, 0x83, 0x9b, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x2d, 0x1f, 0x55, 0xc1, 0x6b, 0x02, 0x00, 0x00,
}
