// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	proto1 "main/internal/microservices/image/proto"
	proto2 "main/internal/microservices/session/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageToUser struct {
	Url                  *proto1.ImageUrl `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id                   *proto2.UserId   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ImageToUser) Reset()         { *m = ImageToUser{} }
func (m *ImageToUser) String() string { return proto.CompactTextString(m) }
func (*ImageToUser) ProtoMessage()    {}
func (*ImageToUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ImageToUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageToUser.Unmarshal(m, b)
}
func (m *ImageToUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageToUser.Marshal(b, m, deterministic)
}
func (m *ImageToUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageToUser.Merge(m, src)
}
func (m *ImageToUser) XXX_Size() int {
	return xxx_messageInfo_ImageToUser.Size(m)
}
func (m *ImageToUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageToUser.DiscardUnknown(m)
}

var xxx_messageInfo_ImageToUser proto.InternalMessageInfo

func (m *ImageToUser) GetUrl() *proto1.ImageUrl {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *ImageToUser) GetId() *proto2.UserId {
	if m != nil {
		return m.Id
	}
	return nil
}

type UserName struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserName) Reset()         { *m = UserName{} }
func (m *UserName) String() string { return proto.CompactTextString(m) }
func (*UserName) ProtoMessage()    {}
func (*UserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserName.Unmarshal(m, b)
}
func (m *UserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserName.Marshal(b, m, deterministic)
}
func (m *UserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserName.Merge(m, src)
}
func (m *UserName) XXX_Size() int {
	return xxx_messageInfo_UserName.Size(m)
}
func (m *UserName) XXX_DiscardUnknown() {
	xxx_messageInfo_UserName.DiscardUnknown(m)
}

var xxx_messageInfo_UserName proto.InternalMessageInfo

func (m *UserName) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	BirthDate            string   `protobuf:"bytes,5,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserData) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *UserData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UserCredentials struct {
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredentials) Reset()         { *m = UserCredentials{} }
func (m *UserCredentials) String() string { return proto.CompactTextString(m) }
func (*UserCredentials) ProtoMessage()    {}
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredentials.Unmarshal(m, b)
}
func (m *UserCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredentials.Marshal(b, m, deterministic)
}
func (m *UserCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredentials.Merge(m, src)
}
func (m *UserCredentials) XXX_Size() int {
	return xxx_messageInfo_UserCredentials.Size(m)
}
func (m *UserCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredentials proto.InternalMessageInfo

func (m *UserCredentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*ImageToUser)(nil), "ImageToUser")
	proto.RegisterType((*UserName)(nil), "UserName")
	proto.RegisterType((*UserData)(nil), "UserData")
	proto.RegisterType((*UserCredentials)(nil), "UserCredentials")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x4d, 0xdb, 0xb5, 0x5b, 0x6e, 0xca, 0x40, 0x16, 0x1a, 0x51, 0x06, 0x12, 0x0a, 0xa8, 0xec,
	0xc9, 0x91, 0x86, 0xe0, 0x7d, 0x74, 0x08, 0x45, 0x9a, 0x40, 0x4a, 0xe9, 0x0b, 0x6f, 0xde, 0x7c,
	0x97, 0x59, 0x4a, 0xe2, 0xc8, 0x76, 0x8a, 0xf8, 0x13, 0x9e, 0xf8, 0x56, 0x64, 0x3b, 0x69, 0x3b,
	0x24, 0x10, 0x7b, 0x6a, 0xcf, 0x3d, 0xd7, 0xd7, 0xc7, 0xf7, 0x9c, 0x00, 0x74, 0x1a, 0x15, 0x6d,
	0x95, 0x34, 0x32, 0x39, 0x2d, 0xa5, 0x2c, 0x2b, 0xcc, 0x1c, 0xba, 0xee, 0x6e, 0x33, 0xac, 0x5b,
	0xf3, 0xa3, 0x27, 0x1f, 0x69, 0xd4, 0x5a, 0xc8, 0xa6, 0x87, 0x91, 0xa8, 0x59, 0x89, 0x1e, 0xa4,
	0x4b, 0x88, 0x72, 0x0b, 0xbf, 0xca, 0xb5, 0x46, 0x45, 0x4e, 0x61, 0xd2, 0xa9, 0x2a, 0x1e, 0xbd,
	0x1c, 0x9d, 0x45, 0xe7, 0x21, 0x75, 0xd4, 0x5a, 0x55, 0x85, 0xad, 0x92, 0x67, 0x30, 0x16, 0x3c,
	0x1e, 0x3b, 0xee, 0x90, 0xda, 0xfe, 0x9c, 0x17, 0x63, 0xc1, 0xd3, 0x05, 0x1c, 0x59, 0xf4, 0x99,
	0xd5, 0x48, 0x92, 0xdd, 0x7f, 0x37, 0x26, 0x2c, 0xb6, 0x38, 0xfd, 0x35, 0xf2, 0xe4, 0x25, 0x33,
	0x8c, 0x1c, 0xc3, 0x38, 0xe7, 0x7d, 0xcb, 0x38, 0xe7, 0xe4, 0x29, 0x4c, 0xb1, 0x66, 0xa2, 0x72,
	0x17, 0x84, 0x85, 0x07, 0x76, 0x5c, 0xcb, 0xb4, 0xfe, 0x2e, 0x15, 0x8f, 0x27, 0x7e, 0xdc, 0x80,
	0x2d, 0x67, 0x57, 0xd0, 0xd8, 0xab, 0x0e, 0x3c, 0x37, 0x60, 0xf2, 0x1c, 0xc2, 0x6b, 0xa1, 0xcc,
	0xdd, 0x25, 0x33, 0x18, 0x4f, 0x1d, 0xb9, 0x2b, 0x90, 0x13, 0x98, 0x5d, 0x6c, 0x98, 0x61, 0x2a,
	0x9e, 0x39, 0xaa, 0x47, 0xe9, 0x12, 0x1e, 0x5b, 0x7d, 0x4b, 0x85, 0x1c, 0x1b, 0x23, 0x58, 0xa5,
	0x1f, 0x2e, 0xeb, 0xfc, 0xe7, 0x04, 0x22, 0x3b, 0x65, 0x85, 0x6a, 0x23, 0x6e, 0x90, 0x64, 0x70,
	0x54, 0x60, 0x29, 0xb4, 0x41, 0x45, 0x42, 0x3a, 0xbc, 0x3f, 0x39, 0xa1, 0xde, 0x33, 0x3a, 0x78,
	0x46, 0x3f, 0x5a, 0xcf, 0xd2, 0x80, 0xbc, 0x81, 0xe9, 0x95, 0x2c, 0xf3, 0x86, 0x3c, 0xa1, 0x7f,
	0xa8, 0x49, 0x80, 0xae, 0xbc, 0x97, 0x39, 0x4f, 0x03, 0xf2, 0x02, 0x0e, 0x2e, 0x3a, 0x73, 0x47,
	0xf6, 0xaa, 0xc9, 0x21, 0x5d, 0x19, 0x66, 0x3a, 0x9d, 0x06, 0x64, 0x01, 0xd1, 0x27, 0x34, 0xce,
	0xa7, 0xe6, 0x56, 0xde, 0xeb, 0xda, 0xe9, 0x48, 0x03, 0x42, 0x61, 0x76, 0x25, 0xcb, 0x2f, 0x9d,
	0xb9, 0xd7, 0xf2, 0x77, 0x7d, 0xef, 0x61, 0xbe, 0x6e, 0x2b, 0xc9, 0xb8, 0xdf, 0x1a, 0x99, 0xd3,
	0xbd, 0x08, 0xfd, 0xe3, 0xdc, 0x6b, 0x98, 0x17, 0x58, 0xcb, 0x0d, 0xf6, 0xe7, 0x86, 0x0c, 0x25,
	0xbb, 0xa0, 0xa5, 0x01, 0x79, 0x07, 0xc7, 0xeb, 0x96, 0x33, 0x83, 0x5b, 0xe1, 0xff, 0xb5, 0xb4,
	0x57, 0xdb, 0xc7, 0xba, 0x18, 0xee, 0xcd, 0xde, 0xc6, 0x2f, 0xf8, 0x70, 0xf6, 0x6d, 0x51, 0x33,
	0xd1, 0x64, 0xa2, 0x31, 0x36, 0x27, 0x55, 0x56, 0x8b, 0x1b, 0x25, 0xb5, 0x37, 0x4a, 0x67, 0x36,
	0x3d, 0xfd, 0x27, 0x34, 0x73, 0x3f, 0x6f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x6a, 0x64,
	0x72, 0x65, 0x03, 0x00, 0x00,
}
