---
apiVersion: v1
kind: Service
metadata:
  name: service-db-redis
  labels:
    app: redis
  namespace: musicon
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: redis
    namespace: musicon
spec:
  serviceName: service-db-redis 
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      namespace: musicon
    spec:
      containers:
      - name: redis
        image: bitnami/redis:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        # - name: REDIS_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #         name: redis-password
        #         key: redis-password
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: data
          mountPath: /bitnami/redis/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
            storage: 5Gi
