INSERT INTO artist_track ( artist_id, track_id ) VALUES
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Gospel' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Last One Standing' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Venom' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Killer' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Black Magic' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred’s Theme' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Tone Deaf' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Book of Rhymes' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Favorite Bitch' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Guns Blazing' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Gnat' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Higher' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'These Demons' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Key' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'She Loves Me' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Killer' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Zeus' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Thus Far' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Discombobulated' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Premonition' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Unaccommodating' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'You Gon’ Learn' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Those Kinda Nights' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'In Too Deep' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Godzilla' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Darkness' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Leaving Heaven' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Yah Yah' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepdad' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepdad' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Marsh' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Never Love Again' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Little Engine' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Lock It Up' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Farewell' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'No Regrets' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'I Will' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'The Adventures Of Moon Man & Slim Shady' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Premonition' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Unaccommodating' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'You Gon’ Learn' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Those Kinda Nights' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'In Too Deep' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Godzilla' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Darkness' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Leaving Heaven' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Yah Yah' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepdad' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepdad' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Marsh' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Never Love Again' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Little Engine' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Lock It Up' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Farewell' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'No Regrets' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'I Will' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Bang' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Killshot' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'The Ringer' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Greatest' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Lucky You' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Paul' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Normal' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Em Calls Paul' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepping Stone' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Not Alike' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Kamikaze' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Fall' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Nice Guy' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Good Guy' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Venom' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Nowhere Fast' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Chloraseptic' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Walk On Water' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Believe' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Chloraseptic' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Untouchable' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'River' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Remind Me (Intro)' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Remind Me' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Revival (Interlude)' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Like Home' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Bad Husband' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Tragic Endings' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Framed' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Nowhere Fast' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Heat' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Offended' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Need Me' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'In Your Head' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Castle' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Arose' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Campaign Speech' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Detroit Vs. Everybody' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Twerk Dat Pop That (feat. Eminem & Royce da 5''9")' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Twerk Dat Pop That (Clean) [feat. Eminem & Royce da 5''9"]' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Bad Guy' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Parking Lot' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Rhyme Or Reason' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'So Much Better' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Survival' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Legacy' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Asshole' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Berzerk' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Rap God' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Brainless' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stronger Than I Was' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'The Monster' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'So Far...' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Love Game' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Headlights' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Evil Twin' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Baby' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Desperation' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Groundhog Day' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Beautiful Pain' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Wicked Ways' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'My Life' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'I Need A Doctor' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Cold Wind Blows' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Talkin’ 2 Myself' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'On Fire' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Won''t Back Down' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'W.T.P.' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Going Through Changes' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Not Afraid' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Seduction' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'No Love' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Space Bound' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Cinderella Man' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = '25 To Life' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'So Bad' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Almost Famous' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Love The Way You Lie' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'You''re Never Over' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Untitled' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Ridaz' ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Session One' ) )
;