INSERT INTO artist_track ( artist_id, track_id ) VALUES
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Gospel' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Last One Standing' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Venom' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Killer' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Black Magic' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred’s Theme' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Tone Deaf' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Book of Rhymes' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Favorite Bitch' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Guns Blazing' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Gnat' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Higher' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'These Demons' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Key' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'She Loves Me' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Killer' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Zeus' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Thus Far' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Discombobulated' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Premonition' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Unaccommodating' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'You Gon’ Learn' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Those Kinda Nights' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'In Too Deep' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Godzilla' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Darkness' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Leaving Heaven' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Yah Yah' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepdad' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepdad' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Marsh' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Never Love Again' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Little Engine' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Lock It Up' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Farewell' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'No Regrets' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'I Will' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'The Adventures Of Moon Man & Slim Shady' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Premonition' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Unaccommodating' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'You Gon’ Learn' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Those Kinda Nights' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'In Too Deep' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Godzilla' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Darkness' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Leaving Heaven' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Yah Yah' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepdad' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepdad' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Marsh' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Never Love Again' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Little Engine' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Lock It Up' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Farewell' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'No Regrets' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'I Will' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Alfred' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Bang' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Killshot' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'The Ringer' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Greatest' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Lucky You' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Paul' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Normal' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Em Calls Paul' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stepping Stone' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Not Alike' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Kamikaze' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Fall' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Nice Guy' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Good Guy' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Venom' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Nowhere Fast' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Chloraseptic' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Walk On Water' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Believe' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Chloraseptic' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Untouchable' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'River' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Remind Me (Intro)' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Remind Me' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Revival (Interlude)' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Like Home' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Bad Husband' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Tragic Endings' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Framed' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Nowhere Fast' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Heat' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Offended' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Need Me' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'In Your Head' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Castle' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Arose' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Campaign Speech' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Detroit Vs. Everybody' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Twerk Dat Pop That (feat. Eminem & Royce da 5''9")' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Twerk Dat Pop That (Clean) [feat. Eminem & Royce da 5''9"]' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Bad Guy' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Parking Lot' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Rhyme Or Reason' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'So Much Better' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Survival' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Legacy' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Asshole' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Berzerk' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Rap God' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Brainless' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Stronger Than I Was' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'The Monster' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'So Far...' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Love Game' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Headlights' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Evil Twin' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Baby' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Desperation' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Groundhog Day' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Beautiful Pain' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Wicked Ways' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'My Life' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'I Need A Doctor' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Cold Wind Blows' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Talkin’ 2 Myself' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'On Fire' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Won''t Back Down' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'W.T.P.' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Going Through Changes' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Not Afraid' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Seduction' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'No Love' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Space Bound' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Cinderella Man' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = '25 To Life' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'So Bad' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Almost Famous' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Love The Way You Lie' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'You''re Never Over' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Untitled' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Ridaz' limit 1 ) ),
( ( SELECT id FROM artist WHERE name = 'Eminem' ), ( SELECT id FROM track WHERE name = 'Session One' limit 1 ) ) on conflict do nothing 
;