{
 "title": "Golden signal",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "rate_interval", "label": "Rate interval", "query": "15s" },
   { "name": "remo", "query": "${VAR_REMO}" },
   { "name": "quantile", "label": "Quantile", "query": "0.95" },
   { "name": "handler", "label": "Handler", "query": "album" }
  ]
 },
 "panels": [
  { "title": "Total request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total{code=~\"4..|5..\"}[$rate_interval])) / sum(rate(musicon_requests_total[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total{handler!=\"\", code=~\"4..|5..\"}[$rate_interval])) / sum(rate(musicon_requests_total{handler!=\"\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total{handler!=\"\"}[$rate_interval])) by(handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total{code=~\"4..|5..\"}[$rate_interval])) by(handler) / sum(rate(musicon_requests_total[$rate_interval])) by(handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(musicon_response_time_seconds_bucket{code=~\"2..\"}[$rate_interval])) by(le)) * 1000",
     "legendFormat": "{{label_name}}total"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(musicon_response_time_seconds_bucket{code=~\"2..\"}[$rate_interval])) by(le, handler)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request for handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total{handler=\"$handler\"}[$rate_interval])) by(path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total{handler=\"$handler\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total{handler=\"$handler\", code=~\"4..|5..\"}[$rate_interval])) by(path) / sum(rate(musicon_requests_total{handler=\"$handler\"}[$rate_interval])) by(path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(musicon_requests_total{code=~\"4..|5..\", handler=\"$handler\"}[$rate_interval])) / sum(rate(musicon_requests_total{handler=\"$handler\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(musicon_response_time_seconds_bucket{code=~\"2..\", handler=\"$handler\"}[$rate_interval])) by(le, path)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Host metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_memory_MemFree_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes[$rate_interval]) - avg_over_time(node_memory_MemFree_bytes[$rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes[$rate_interval]) ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes[$rate_interval]) - avg_over_time(node_memory_MemFree_bytes[$rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes[$rate_interval]) ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}[$rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}