// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playlist.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	proto1 "main/internal/microservices/image/proto"
	_ "main/internal/microservices/session/proto"
	proto2 "main/internal/microservices/track/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsLikedPlaylist struct {
	IsLiked              bool     `protobuf:"varint,1,opt,name=IsLiked,proto3" json:"IsLiked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsLikedPlaylist) Reset()         { *m = IsLikedPlaylist{} }
func (m *IsLikedPlaylist) String() string { return proto.CompactTextString(m) }
func (*IsLikedPlaylist) ProtoMessage()    {}
func (*IsLikedPlaylist) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{0}
}

func (m *IsLikedPlaylist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLikedPlaylist.Unmarshal(m, b)
}
func (m *IsLikedPlaylist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLikedPlaylist.Marshal(b, m, deterministic)
}
func (m *IsLikedPlaylist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLikedPlaylist.Merge(m, src)
}
func (m *IsLikedPlaylist) XXX_Size() int {
	return xxx_messageInfo_IsLikedPlaylist.Size(m)
}
func (m *IsLikedPlaylist) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLikedPlaylist.DiscardUnknown(m)
}

var xxx_messageInfo_IsLikedPlaylist proto.InternalMessageInfo

func (m *IsLikedPlaylist) GetIsLiked() bool {
	if m != nil {
		return m.IsLiked
	}
	return false
}

type HasAccess struct {
	IsAccess             bool     `protobuf:"varint,1,opt,name=IsAccess,proto3" json:"IsAccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasAccess) Reset()         { *m = HasAccess{} }
func (m *HasAccess) String() string { return proto.CompactTextString(m) }
func (*HasAccess) ProtoMessage()    {}
func (*HasAccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{1}
}

func (m *HasAccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasAccess.Unmarshal(m, b)
}
func (m *HasAccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasAccess.Marshal(b, m, deterministic)
}
func (m *HasAccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasAccess.Merge(m, src)
}
func (m *HasAccess) XXX_Size() int {
	return xxx_messageInfo_HasAccess.Size(m)
}
func (m *HasAccess) XXX_DiscardUnknown() {
	xxx_messageInfo_HasAccess.DiscardUnknown(m)
}

var xxx_messageInfo_HasAccess proto.InternalMessageInfo

func (m *HasAccess) GetIsAccess() bool {
	if m != nil {
		return m.IsAccess
	}
	return false
}

type PlaylistToUserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PlaylistId           uint64   `protobuf:"varint,2,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaylistToUserId) Reset()         { *m = PlaylistToUserId{} }
func (m *PlaylistToUserId) String() string { return proto.CompactTextString(m) }
func (*PlaylistToUserId) ProtoMessage()    {}
func (*PlaylistToUserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{2}
}

func (m *PlaylistToUserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistToUserId.Unmarshal(m, b)
}
func (m *PlaylistToUserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistToUserId.Marshal(b, m, deterministic)
}
func (m *PlaylistToUserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistToUserId.Merge(m, src)
}
func (m *PlaylistToUserId) XXX_Size() int {
	return xxx_messageInfo_PlaylistToUserId.Size(m)
}
func (m *PlaylistToUserId) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistToUserId.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistToUserId proto.InternalMessageInfo

func (m *PlaylistToUserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PlaylistToUserId) GetPlaylistId() uint64 {
	if m != nil {
		return m.PlaylistId
	}
	return 0
}

type PlaylistId struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaylistId) Reset()         { *m = PlaylistId{} }
func (m *PlaylistId) String() string { return proto.CompactTextString(m) }
func (*PlaylistId) ProtoMessage()    {}
func (*PlaylistId) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{3}
}

func (m *PlaylistId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistId.Unmarshal(m, b)
}
func (m *PlaylistId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistId.Marshal(b, m, deterministic)
}
func (m *PlaylistId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistId.Merge(m, src)
}
func (m *PlaylistId) XXX_Size() int {
	return xxx_messageInfo_PlaylistId.Size(m)
}
func (m *PlaylistId) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistId.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistId proto.InternalMessageInfo

func (m *PlaylistId) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PlaylistToTrackId struct {
	PlaylistId           uint64   `protobuf:"varint,1,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
	TrackId              uint64   `protobuf:"varint,2,opt,name=trackId,proto3" json:"trackId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaylistToTrackId) Reset()         { *m = PlaylistToTrackId{} }
func (m *PlaylistToTrackId) String() string { return proto.CompactTextString(m) }
func (*PlaylistToTrackId) ProtoMessage()    {}
func (*PlaylistToTrackId) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{4}
}

func (m *PlaylistToTrackId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistToTrackId.Unmarshal(m, b)
}
func (m *PlaylistToTrackId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistToTrackId.Marshal(b, m, deterministic)
}
func (m *PlaylistToTrackId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistToTrackId.Merge(m, src)
}
func (m *PlaylistToTrackId) XXX_Size() int {
	return xxx_messageInfo_PlaylistToTrackId.Size(m)
}
func (m *PlaylistToTrackId) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistToTrackId.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistToTrackId proto.InternalMessageInfo

func (m *PlaylistToTrackId) GetPlaylistId() uint64 {
	if m != nil {
		return m.PlaylistId
	}
	return 0
}

func (m *PlaylistToTrackId) GetTrackId() uint64 {
	if m != nil {
		return m.TrackId
	}
	return 0
}

type PlaylistIdToImageUrl struct {
	Id                   uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  *proto1.ImageUrl `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PlaylistIdToImageUrl) Reset()         { *m = PlaylistIdToImageUrl{} }
func (m *PlaylistIdToImageUrl) String() string { return proto.CompactTextString(m) }
func (*PlaylistIdToImageUrl) ProtoMessage()    {}
func (*PlaylistIdToImageUrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{5}
}

func (m *PlaylistIdToImageUrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistIdToImageUrl.Unmarshal(m, b)
}
func (m *PlaylistIdToImageUrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistIdToImageUrl.Marshal(b, m, deterministic)
}
func (m *PlaylistIdToImageUrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistIdToImageUrl.Merge(m, src)
}
func (m *PlaylistIdToImageUrl) XXX_Size() int {
	return xxx_messageInfo_PlaylistIdToImageUrl.Size(m)
}
func (m *PlaylistIdToImageUrl) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistIdToImageUrl.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistIdToImageUrl proto.InternalMessageInfo

func (m *PlaylistIdToImageUrl) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlaylistIdToImageUrl) GetUrl() *proto1.ImageUrl {
	if m != nil {
		return m.Url
	}
	return nil
}

type PlaylistBase struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatorId            string   `protobuf:"bytes,3,opt,name=CreatorId,proto3" json:"CreatorId,omitempty"`
	Preview              string   `protobuf:"bytes,4,opt,name=Preview,proto3" json:"Preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaylistBase) Reset()         { *m = PlaylistBase{} }
func (m *PlaylistBase) String() string { return proto.CompactTextString(m) }
func (*PlaylistBase) ProtoMessage()    {}
func (*PlaylistBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{6}
}

func (m *PlaylistBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistBase.Unmarshal(m, b)
}
func (m *PlaylistBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistBase.Marshal(b, m, deterministic)
}
func (m *PlaylistBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistBase.Merge(m, src)
}
func (m *PlaylistBase) XXX_Size() int {
	return xxx_messageInfo_PlaylistBase.Size(m)
}
func (m *PlaylistBase) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistBase.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistBase proto.InternalMessageInfo

func (m *PlaylistBase) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlaylistBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaylistBase) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *PlaylistBase) GetPreview() string {
	if m != nil {
		return m.Preview
	}
	return ""
}

type PlaylistResponse struct {
	Id                   uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Preview              string                 `protobuf:"bytes,3,opt,name=Preview,proto3" json:"Preview,omitempty"`
	CreatorName          string                 `protobuf:"bytes,4,opt,name=CreatorName,proto3" json:"CreatorName,omitempty"`
	CreatorId            string                 `protobuf:"bytes,6,opt,name=CreatorId,proto3" json:"CreatorId,omitempty"`
	IsYours              bool                   `protobuf:"varint,7,opt,name=IsYours,proto3" json:"IsYours,omitempty"`
	Tracks               *proto2.TracksResponse `protobuf:"bytes,8,opt,name=Tracks,proto3" json:"Tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PlaylistResponse) Reset()         { *m = PlaylistResponse{} }
func (m *PlaylistResponse) String() string { return proto.CompactTextString(m) }
func (*PlaylistResponse) ProtoMessage()    {}
func (*PlaylistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{7}
}

func (m *PlaylistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistResponse.Unmarshal(m, b)
}
func (m *PlaylistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistResponse.Marshal(b, m, deterministic)
}
func (m *PlaylistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistResponse.Merge(m, src)
}
func (m *PlaylistResponse) XXX_Size() int {
	return xxx_messageInfo_PlaylistResponse.Size(m)
}
func (m *PlaylistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistResponse proto.InternalMessageInfo

func (m *PlaylistResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlaylistResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaylistResponse) GetPreview() string {
	if m != nil {
		return m.Preview
	}
	return ""
}

func (m *PlaylistResponse) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

func (m *PlaylistResponse) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *PlaylistResponse) GetIsYours() bool {
	if m != nil {
		return m.IsYours
	}
	return false
}

func (m *PlaylistResponse) GetTracks() *proto2.TracksResponse {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type PlaylistsResponse struct {
	Playlists            []*PlaylistResponse `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PlaylistsResponse) Reset()         { *m = PlaylistsResponse{} }
func (m *PlaylistsResponse) String() string { return proto.CompactTextString(m) }
func (*PlaylistsResponse) ProtoMessage()    {}
func (*PlaylistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{8}
}

func (m *PlaylistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistsResponse.Unmarshal(m, b)
}
func (m *PlaylistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistsResponse.Marshal(b, m, deterministic)
}
func (m *PlaylistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistsResponse.Merge(m, src)
}
func (m *PlaylistsResponse) XXX_Size() int {
	return xxx_messageInfo_PlaylistsResponse.Size(m)
}
func (m *PlaylistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistsResponse proto.InternalMessageInfo

func (m *PlaylistsResponse) GetPlaylists() []*PlaylistResponse {
	if m != nil {
		return m.Playlists
	}
	return nil
}

type PlaylistsBase struct {
	Playlists            []*PlaylistBase `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlaylistsBase) Reset()         { *m = PlaylistsBase{} }
func (m *PlaylistsBase) String() string { return proto.CompactTextString(m) }
func (*PlaylistsBase) ProtoMessage()    {}
func (*PlaylistsBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{9}
}

func (m *PlaylistsBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaylistsBase.Unmarshal(m, b)
}
func (m *PlaylistsBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaylistsBase.Marshal(b, m, deterministic)
}
func (m *PlaylistsBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaylistsBase.Merge(m, src)
}
func (m *PlaylistsBase) XXX_Size() int {
	return xxx_messageInfo_PlaylistsBase.Size(m)
}
func (m *PlaylistsBase) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaylistsBase.DiscardUnknown(m)
}

var xxx_messageInfo_PlaylistsBase proto.InternalMessageInfo

func (m *PlaylistsBase) GetPlaylists() []*PlaylistBase {
	if m != nil {
		return m.Playlists
	}
	return nil
}

func init() {
	proto.RegisterType((*IsLikedPlaylist)(nil), "IsLikedPlaylist")
	proto.RegisterType((*HasAccess)(nil), "HasAccess")
	proto.RegisterType((*PlaylistToUserId)(nil), "PlaylistToUserId")
	proto.RegisterType((*PlaylistId)(nil), "PlaylistId")
	proto.RegisterType((*PlaylistToTrackId)(nil), "PlaylistToTrackId")
	proto.RegisterType((*PlaylistIdToImageUrl)(nil), "PlaylistIdToImageUrl")
	proto.RegisterType((*PlaylistBase)(nil), "PlaylistBase")
	proto.RegisterType((*PlaylistResponse)(nil), "PlaylistResponse")
	proto.RegisterType((*PlaylistsResponse)(nil), "PlaylistsResponse")
	proto.RegisterType((*PlaylistsBase)(nil), "PlaylistsBase")
}

func init() {
	proto.RegisterFile("playlist.proto", fileDescriptor_073b59cb25aac063)
}

var fileDescriptor_073b59cb25aac063 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xce, 0x49, 0x6e, 0x32, 0xfe, 0xd3, 0xb4, 0xab, 0x9f, 0x2a, 0x4a, 0x2b, 0x54, 0xed, 0x4d,
	0x4b, 0x5b, 0xd6, 0x52, 0x0a, 0x12, 0x12, 0x5c, 0xd0, 0x03, 0x6a, 0x8d, 0x28, 0x8a, 0x4c, 0x73,
	0x01, 0x77, 0xdb, 0x78, 0x5a, 0x2d, 0x75, 0xe2, 0xc8, 0xeb, 0x04, 0xe5, 0x65, 0x78, 0x29, 0x5e,
	0x08, 0x79, 0xbd, 0x6b, 0xc7, 0x49, 0x8a, 0x02, 0x57, 0xf1, 0xb7, 0x33, 0xdf, 0x37, 0x87, 0xdd,
	0x99, 0xc0, 0xe6, 0x38, 0xe0, 0xb3, 0x40, 0xc8, 0x98, 0x8d, 0xa3, 0x30, 0x0e, 0x3b, 0xbb, 0x0f,
	0x61, 0xf8, 0x10, 0xa0, 0xa3, 0xd0, 0xdd, 0xe4, 0xde, 0xc1, 0xe1, 0x38, 0x9e, 0x69, 0xa3, 0x1d,
	0x47, 0x7c, 0xf0, 0xa8, 0x41, 0x53, 0xa2, 0x94, 0x22, 0x1c, 0x19, 0x9b, 0x18, 0xf2, 0x07, 0x4c,
	0x01, 0x3d, 0x86, 0x96, 0x2b, 0x3f, 0x89, 0x47, 0xf4, 0x7b, 0x5a, 0x9e, 0xb4, 0x61, 0x43, 0x1f,
	0xb5, 0xcb, 0xfb, 0xe5, 0xc3, 0xba, 0x67, 0x20, 0x3d, 0x80, 0xc6, 0x35, 0x97, 0x67, 0x83, 0x01,
	0x4a, 0x49, 0x3a, 0x50, 0x77, 0xf5, 0xb7, 0xf6, 0xcb, 0x30, 0xfd, 0x08, 0x5b, 0x46, 0xee, 0x36,
	0xec, 0x4b, 0x8c, 0x5c, 0x9f, 0xec, 0x80, 0x35, 0x51, 0x5f, 0xca, 0xbb, 0xe1, 0x69, 0x44, 0x9e,
	0x03, 0x98, 0xca, 0x5c, 0xbf, 0x5d, 0xd9, 0x2f, 0x1f, 0xd6, 0xbc, 0xb9, 0x13, 0xba, 0x07, 0xd0,
	0xcb, 0x10, 0xd9, 0x84, 0x8a, 0x48, 0x15, 0x6a, 0x5e, 0x45, 0xf8, 0xf4, 0x06, 0xb6, 0xf3, 0x48,
	0xb7, 0x49, 0xd1, 0x4b, 0x92, 0xe5, 0x45, 0xc9, 0xa4, 0xc2, 0x38, 0x75, 0xd5, 0xf1, 0x0c, 0xa4,
	0x17, 0xf0, 0x7f, 0x1e, 0xec, 0x36, 0x74, 0x93, 0x4e, 0xf5, 0xa3, 0x60, 0x31, 0x2c, 0xd9, 0x85,
	0xea, 0x24, 0x0a, 0x14, 0xdb, 0xee, 0x36, 0x98, 0xf1, 0xf3, 0x92, 0x53, 0xfa, 0x1d, 0xfe, 0x33,
	0x22, 0xe7, 0x5c, 0x62, 0x42, 0xce, 0xd2, 0xa8, 0xb8, 0x3e, 0x21, 0x50, 0xfb, 0xcc, 0x87, 0xa8,
	0xd8, 0x0d, 0x4f, 0x7d, 0x93, 0x3d, 0x68, 0x5c, 0x44, 0xc8, 0xe3, 0x30, 0x69, 0x50, 0x55, 0x19,
	0xf2, 0x83, 0x24, 0xe1, 0x5e, 0x84, 0x53, 0x81, 0x3f, 0xda, 0x35, 0x65, 0x33, 0x90, 0xfe, 0x2a,
	0xe7, 0xad, 0xf6, 0x50, 0x8e, 0xc3, 0xd1, 0x9a, 0x01, 0xe7, 0x24, 0xab, 0x05, 0x49, 0xb2, 0x0f,
	0xb6, 0x8e, 0xac, 0x48, 0x69, 0xc0, 0xf9, 0xa3, 0x62, 0xb2, 0xd6, 0x8a, 0x64, 0x5d, 0xf9, 0x35,
	0x9c, 0x44, 0xb2, 0xbd, 0x61, 0xde, 0x8f, 0x82, 0xe4, 0x00, 0x2c, 0x75, 0x45, 0xb2, 0x5d, 0x57,
	0x8d, 0x6b, 0xb1, 0x14, 0x9a, 0xc4, 0x3d, 0x6d, 0xa6, 0x97, 0xf9, 0xad, 0x66, 0x46, 0xe2, 0x40,
	0xc3, 0xdc, 0x61, 0xf2, 0xe2, 0xaa, 0x87, 0x76, 0x77, 0x9b, 0x2d, 0xd6, 0xee, 0xe5, 0x3e, 0xf4,
	0x1d, 0x34, 0x33, 0x15, 0x75, 0x11, 0xc7, 0xcb, 0x0a, 0x4d, 0x36, 0x7f, 0x55, 0x73, 0xec, 0xee,
	0x4f, 0x0b, 0x5a, 0xc6, 0xf6, 0x05, 0xa3, 0xa9, 0x18, 0x20, 0x39, 0x01, 0x4b, 0xd5, 0x89, 0xa4,
	0xc8, 0xeb, 0x2c, 0x27, 0x42, 0x4b, 0xe4, 0x25, 0x54, 0xaf, 0x30, 0x26, 0xb9, 0xcd, 0xcc, 0xc2,
	0x53, 0xee, 0x5b, 0x57, 0x18, 0x27, 0x1e, 0x59, 0xd6, 0x64, 0x83, 0x69, 0xc6, 0x26, 0x2b, 0x94,
	0x42, 0x4b, 0xe4, 0x0d, 0xd4, 0xcf, 0x7c, 0x5f, 0x35, 0x8c, 0x10, 0xb6, 0x34, 0x04, 0x9d, 0x1d,
	0x96, 0x2e, 0x08, 0x66, 0x16, 0x04, 0xfb, 0x90, 0x2c, 0x08, 0x5a, 0x22, 0x6f, 0xc1, 0xf6, 0x70,
	0x18, 0x4e, 0xf1, 0x5f, 0xc8, 0xef, 0xa1, 0xd9, 0x1f, 0xfb, 0x3c, 0x46, 0xf3, 0x5c, 0x9e, 0xb1,
	0x55, 0x13, 0xf3, 0x07, 0x85, 0x17, 0xd0, 0x4c, 0xc3, 0x1b, 0x05, 0x7b, 0x4e, 0xa1, 0x93, 0x0f,
	0x13, 0x2d, 0x91, 0x53, 0x80, 0x4b, 0x0c, 0x30, 0xc6, 0xf3, 0x99, 0xeb, 0x17, 0xfd, 0x9e, 0xd6,
	0x3f, 0x85, 0x5a, 0xb2, 0xae, 0x56, 0xf5, 0xfd, 0x69, 0x92, 0x03, 0x56, 0xba, 0xe5, 0x56, 0xd1,
	0xb6, 0xd8, 0xc2, 0x8e, 0xa4, 0x25, 0xf2, 0x1a, 0xac, 0xfe, 0x28, 0xf8, 0xeb, 0x38, 0x5d, 0x68,
	0x5d, 0x73, 0x79, 0x13, 0xfa, 0xe2, 0x7e, 0xa6, 0x17, 0xe9, 0x0a, 0x3e, 0xb0, 0x6c, 0xcf, 0xd2,
	0x12, 0x39, 0x82, 0xe6, 0x35, 0x97, 0x1e, 0x72, 0x5f, 0x33, 0x0a, 0x8d, 0x28, 0xfa, 0xbe, 0x02,
	0xfb, 0x86, 0x3f, 0x62, 0x2f, 0x12, 0xd3, 0xe4, 0x99, 0xae, 0xdd, 0x32, 0x50, 0xac, 0xc9, 0x5d,
	0x20, 0x06, 0x6b, 0x92, 0xce, 0x4f, 0xbe, 0x1d, 0x0d, 0xb9, 0x18, 0x39, 0x62, 0x14, 0x63, 0x34,
	0xe2, 0x81, 0x33, 0x14, 0x83, 0x28, 0x94, 0xe9, 0xa8, 0x48, 0xc7, 0x4c, 0x92, 0xfe, 0x83, 0xb2,
	0xd4, 0xcf, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xb8, 0x06, 0x04, 0xc7, 0x06, 0x00,
	0x00,
}
