---
apiVersion: v1
kind: Service
metadata:
  name: images
  labels:
    app: image-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
  - port: 8087
    name: image
  selector:
    app: image-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deploy
  labels:
    app: image-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-svc
  template:
    metadata:
      labels:
        app: image-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: image
        image: registry.musicon.space/images
        imagePullPolicy: Always
        command: ["/images"]
        env:
        - name: DATABASE_URL
          value: "postgres://musicon@musicon.space:5433/musicon"
