# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#     name: app-config
#     namesapce: musicon
# data:
#   config.json: |-
#     {
#         "service-db-redis": "service-db-redis"
#     }
---
apiVersion: v1
kind: Service
metadata:
  name: session
  labels:
    app: session-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
  - port: 8082
    name: session
  selector:
    app: session-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-deploy
  labels:
    app: session-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-svc
  template:
    metadata:
      labels:
        app: session-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: session
        image: registry.musicon.space/session:1.0
        imagePullPolicy: IfNotPresent
        command: ["/session"]
        env:
        - name: DATABASE_URL
          value: "postgres://musicon:musicon@musicon.space:5432/musicon"
      #   volumeMounts:
      #   - name: config-volume
      #     mountPath: /app/config.json
      #     subPath: config.json
      # volumes:
      #   - name: config-volume
      # configMap:
      #   name: app-config
