---
apiVersion: v1
kind: Service
metadata:
  name: session
  labels:
    app: session-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
  - port: 8082
    name: session
  selector:
    app: session-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-deploy
  labels:
    app: session-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-svc
  template:
    metadata:
      labels:
        app: session-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: session
        image: registry.musicon.space/session
        imagePullPolicy: Always
        command: ["/session"]
        env:
        - name: DATABASE_URL
          value: "postgres://musicon@musicon.space:5433/musicon"
