---
apiVersion: v1
kind: Service
metadata:
  name: survey
  labels:
    app: survey-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
  - port: 8088
    name: survey
  selector:
    app: survey-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-deploy
  labels:
    app: survey-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-svc
  template:
    metadata:
      labels:
        app: survey-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: survey
        image: registry.musicon.space/survey
        imagePullPolicy: Always
        command: ["/survey"]
        env:
        - name: DATABASE_URL
          value: "postgres://musicon@musicon.space:5433/musicon"