// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/album/{id}": {
            "get": {
                "description": "Return album info with all tracks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "album"
                ],
                "summary": "AlbumTracks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "album id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/album.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/album/{id}/is_like": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Check if album is liked",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "album"
                ],
                "summary": "IsLike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "album id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.IsLiked"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/album/{id}/like": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Like album",
                "tags": [
                    "album"
                ],
                "summary": "Like",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "album id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/album/{id}/unlike": {
            "delete": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Unlike album",
                "tags": [
                    "album"
                ],
                "summary": "Unlike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "album id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/artist/{id}": {
            "get": {
                "description": "Return artist info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artist"
                ],
                "summary": "ArtistInfo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "artist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/artist.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/artist/{id}/is_like": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Check if artist is liked",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artist"
                ],
                "summary": "IsLike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "artist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.IsLiked"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/artist/{id}/like": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Like artist",
                "tags": [
                    "artist"
                ],
                "summary": "Like",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "artist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/artist/{id}/unlike": {
            "delete": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Unlike artist",
                "tags": [
                    "artist"
                ],
                "summary": "Unlike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "artist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Check user's authentication by cookie and set csrf-token",
                "tags": [
                    "user"
                ],
                "summary": "Auth",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "Set X-Csrf-Token in Cookie"
                            },
                            "X-Csrf-Token": {
                                "type": "string",
                                "description": "Set X-Csrf-Token in header"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/collection/albums": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Return user's album collection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "album"
                ],
                "summary": "CollectionAlbum",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/album.LikedAlbums"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/collection/artists": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Return user's artist collection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "artist"
                ],
                "summary": "CollectionArtist",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/artist.LikedArtists"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/collection/playlists": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Return user's playlist collection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlist"
                ],
                "summary": "CollectionPlaylist",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/playlist.Base"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/collection/tracks": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Get user tracks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "track"
                ],
                "summary": "GetUserTracks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/track.LikedTracks"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/feed": {
            "get": {
                "description": "Return all albums",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "album"
                ],
                "summary": "Feed",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/album.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/listen": {
            "post": {
                "security": [
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Listen track",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "track"
                ],
                "summary": "Listen",
                "parameters": [
                    {
                        "description": "track id",
                        "name": "trackId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "security": [
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Login user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "User email and password",
                        "name": "userCrds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_domain.UserCredentials"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "Set JSESSIONID in Cookie"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Logout user",
                "tags": [
                    "user"
                ],
                "summary": "LogOut",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Get user info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Me",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_domain.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/most_liked": {
            "get": {
                "description": "Return albums sorted by likes count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "album"
                ],
                "summary": "MostLiked",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/album.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/new": {
            "get": {
                "description": "Return new albums",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "album"
                ],
                "summary": "New",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/album.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Create playlist",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlist"
                ],
                "summary": "Create",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/playlist.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}": {
            "get": {
                "description": "Return playlist info and tracks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlist"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/playlist.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Delete playlist",
                "tags": [
                    "playlist"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/add_track": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Add track to playlist",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "playlist"
                ],
                "summary": "AddTrack",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "track id",
                        "name": "trackId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/track.Id"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/is_creator": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Check if user is creator of playlist",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlist"
                ],
                "summary": "IsCreator",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/playlist.IsCreator"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/is_like": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Check if playlist is liked",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlist"
                ],
                "summary": "IsLike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.IsLiked"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/like": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Like playlist",
                "tags": [
                    "playlist"
                ],
                "summary": "Like",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/make_private": {
            "put": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Make playlist private",
                "tags": [
                    "playlist"
                ],
                "summary": "MakePrivate",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/make_public": {
            "put": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Make playlist public",
                "tags": [
                    "playlist"
                ],
                "summary": "MakePublic",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/remove_track": {
            "delete": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Remove track from playlist",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "playlist"
                ],
                "summary": "RemoveTrack",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "track id",
                        "name": "trackId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/track.Id"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/unlike": {
            "delete": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Unlike playlist",
                "tags": [
                    "playlist"
                ],
                "summary": "Unlike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/update_name": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Update playlist name",
                "tags": [
                    "playlist"
                ],
                "summary": "UpdateName",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "playlist name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/playlist.Name"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlist/{id}/update_preview": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Update playlist preview",
                "tags": [
                    "playlist"
                ],
                "summary": "UpdatePreview",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "preview image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/popular": {
            "get": {
                "description": "Return albums sorted by listen count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "album"
                ],
                "summary": "Popular",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/album.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/remove_avatar": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Remove user images",
                "tags": [
                    "user"
                ],
                "summary": "RemoveAvatar",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sign_up": {
            "post": {
                "security": [
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Register user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "SignUp",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_domain.User"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "Set JSESSIONID in Cookie"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/track/{id}": {
            "get": {
                "description": "Return album that contain required track",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "album"
                ],
                "summary": "AlbumWithRequiredTrack",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "track id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/album.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/track/{id}/is_like": {
            "get": {
                "security": [
                    {
                        "cookieAuth": []
                    }
                ],
                "description": "Check if track is liked",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "track"
                ],
                "summary": "IsLike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "track id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.IsLiked"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/track/{id}/like": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Like track",
                "tags": [
                    "track"
                ],
                "summary": "Like",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "track id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/track/{id}/unlike": {
            "delete": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Unlike track",
                "tags": [
                    "track"
                ],
                "summary": "Unlike",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "track id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update_info": {
            "put": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Update user info",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "UpdateUserInfo",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_domain.User"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload_avatar": {
            "post": {
                "security": [
                    {
                        "cookieAuth": []
                    },
                    {
                        "csrfToken": []
                    },
                    {
                        "cookieCsrfToken": []
                    }
                ],
                "description": "Upload user images",
                "tags": [
                    "user"
                ],
                "summary": "UploadAvatar",
                "parameters": [
                    {
                        "type": "file",
                        "description": "User images",
                        "name": "Avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_domain.UploadAvatarResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "album.Base": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "integer",
                    "example": 1
                },
                "Name": {
                    "type": "string",
                    "example": "AlbumName"
                },
                "Preview": {
                    "type": "string",
                    "example": "AlbumPreview"
                }
            }
        },
        "album.LikedAlbums": {
            "type": "object",
            "properties": {
                "Albums": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/album.Base"
                    }
                }
            }
        },
        "album.Response": {
            "type": "object",
            "properties": {
                "ArtistId": {
                    "type": "integer",
                    "example": 1
                },
                "ArtistName": {
                    "type": "string",
                    "example": "ArtistName"
                },
                "Id": {
                    "type": "integer",
                    "example": 1
                },
                "Name": {
                    "type": "string",
                    "example": "AlbumName"
                },
                "Preview": {
                    "type": "string",
                    "example": "AlbumPreview"
                },
                "Tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/track.Response"
                    }
                }
            }
        },
        "artist.Base": {
            "type": "object",
            "properties": {
                "Avatar": {
                    "type": "string",
                    "example": "ArtistAvatar"
                },
                "Id": {
                    "type": "integer",
                    "example": 1
                },
                "Name": {
                    "type": "string",
                    "example": "ArtistName"
                }
            }
        },
        "artist.LikedArtists": {
            "type": "object",
            "properties": {
                "Artists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/artist.Base"
                    }
                }
            }
        },
        "artist.Response": {
            "type": "object",
            "properties": {
                "Albums": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/album.Base"
                    }
                },
                "Avatar": {
                    "type": "string",
                    "example": "ArtistAvatar"
                },
                "Id": {
                    "type": "integer",
                    "example": 1
                },
                "Name": {
                    "type": "string",
                    "example": "ArtistName"
                },
                "Tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/track.Response"
                    }
                }
            }
        },
        "playlist.Base": {
            "type": "object",
            "properties": {
                "AuthorId": {
                    "type": "string",
                    "example": "sdfa-asdf-adsf"
                },
                "Id": {
                    "type": "integer",
                    "example": 1
                },
                "Name": {
                    "type": "string",
                    "example": "PlaylistName"
                },
                "Preview": {
                    "type": "string",
                    "example": "PlaylistPreview"
                }
            }
        },
        "playlist.IsCreator": {
            "type": "object",
            "properties": {
                "IsCreator": {
                    "type": "boolean"
                }
            }
        },
        "playlist.Name": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string",
                    "example": "PlaylistName"
                }
            }
        },
        "playlist.Response": {
            "type": "object",
            "properties": {
                "AuthorId": {
                    "type": "string",
                    "example": "sdfa-asdf-adsf"
                },
                "AuthorName": {
                    "type": "string",
                    "example": "username"
                },
                "Id": {
                    "type": "integer",
                    "example": 1
                },
                "Name": {
                    "type": "string",
                    "example": "PlaylistName"
                },
                "Preview": {
                    "type": "string",
                    "example": "PlaylistPreview"
                },
                "tracks": {
                    "description": "IsYours    bool   ` + "`" + `json:\"IsYours\" example:\"true\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/track.Response"
                    }
                }
            }
        },
        "response.IsLiked": {
            "type": "object",
            "properties": {
                "IsLiked": {
                    "type": "boolean"
                }
            }
        },
        "track.Id": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "track.LikedTracks": {
            "type": "object",
            "properties": {
                "Tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/track.Response"
                    }
                }
            }
        },
        "track.Response": {
            "type": "object",
            "properties": {
                "ArtistId": {
                    "type": "integer",
                    "example": 1
                },
                "ArtistName": {
                    "type": "string",
                    "example": "ArtiName"
                },
                "Content": {
                    "type": "string",
                    "example": "TrackContent"
                },
                "Duration": {
                    "type": "string",
                    "example": "1:20"
                },
                "Id": {
                    "type": "integer",
                    "example": 1
                },
                "IsLiked": {
                    "type": "boolean",
                    "example": false
                },
                "Name": {
                    "type": "string",
                    "example": "TrackName"
                },
                "Preview": {
                    "type": "string",
                    "example": "TrackPreview"
                }
            }
        },
        "user_domain.UploadAvatarResponse": {
            "type": "object",
            "properties": {
                "AvatarUrl": {
                    "type": "string",
                    "example": "/user-images/images.png"
                }
            }
        },
        "user_domain.User": {
            "type": "object",
            "properties": {
                "Avatar": {
                    "type": "string",
                    "example": "http://test/images/1.jpg,http://test/images/2.jpg"
                },
                "BirthDate": {
                    "type": "string",
                    "example": "2000-01-01"
                },
                "Email": {
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "Id": {
                    "type": "string",
                    "example": "qwer-werw-we4w"
                },
                "Password": {
                    "type": "string",
                    "example": "password"
                },
                "Username": {
                    "type": "string",
                    "example": "john"
                }
            }
        },
        "user_domain.UserCredentials": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "Password": {
                    "type": "string",
                    "example": "password"
                }
            }
        }
    },
    "securityDefinitions": {
        "cookieAuth": {
            "type": "apiKey",
            "name": "JSESSIONID",
            "in": "cookie"
        },
        "cookieCsrfToken": {
            "type": "apiKey",
            "name": "X-Csrf-Token",
            "in": "cookie"
        },
        "csrfToken": {
            "type": "apiKey",
            "name": "X-Csrf-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "musicon.space",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "MusicOn API",
	Description:      "Music web app",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
