global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'musicon'
    static_configs:
      - targets: ['musicon:8080']

remote_write:
  - url: 'http://grafana:3000'
    basic_auth:
      username: 'admin'
      password: 'Music0nSecure'