---
apiVersion: v1
kind: Service
metadata:
  name: candidate
  labels:
    app: candidate-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
    - port: 8088
      name: candidate
  selector:
    app: candidate-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate-deploy
  labels:
    app: candidate-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidate-svc
  template:
    metadata:
      labels:
        app: candidate-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: candidate
          image: registry.musicon.space/candidate
          imagePullPolicy: Always
          command: ["/candidate"]
          env:
            - name: DATABASE_URL
              value: "postgres://musicon@musicon.space:5433/musicon"
