---
apiVersion: v1
kind: Service
metadata:
  name: mailer
  labels:
    app: mailer-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
  - port: 8088
    name: mailer
  selector:
    app: mailer-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-deploy
  labels:
    app: mailer-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-svc
  template:
    metadata:
      labels:
        app: mailer-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: mailer
        image: registry.musicon.space/mailer
        imagePullPolicy: Always
        command: ["/mailer"]
        env:
        - name: SMTP_SERVER_PORT
          value: 587
        - name: SMTP_SERVER_HOST
          value: "live.smtp.mailtrap.io"
        - name: SMTP_SERVER_USERNAME
          value: "api"
        - name: SMTP_SERVER_SENDER
          value: "noreply@musicon.space"
        - name: SMTP_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-server-credentials
              key: SMTP_SERVER_PASSWORD
