---
apiVersion: v1
kind: Service
metadata:
  name: onboarding
  labels:
    app: onboarding-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
    - port: 8091
      name: onboarding
  selector:
    app: onboarding-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-deploy
  labels:
    app: onboarding-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding-svc
  template:
    metadata:
      labels:
        app: onboarding-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: onboarding
          image: registry.musicon.space/onboarding
          imagePullPolicy: Always
          command: ["/onboarding"]
          env:
            - name: DATABASE_URL
              value: "postgres://musicon@musicon.space:5433/musicon"
