---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
  - port: 8081
    name: user
  selector:
    app: user-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    app: user-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: user
        image: registry.musicon.space/user
        imagePullPolicy: Always
        command: ["/user"]
        env:
        - name: DATABASE_URL
          value: "postgres://musicon@musicon.space:5433/musicon"
