---
apiVersion: v1
kind: Service
metadata:
  name: wave
  labels:
    app: wave-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
    - port: 8092
      name: wave
  selector:
    app: wave-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-deploy
  labels:
    app: wave-svc
  namespace: musicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-svc
  template:
    metadata:
      labels:
        app: wave-svc
      namespace: musicon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: wave
          image: registry.musicon.space/wave
          imagePullPolicy: Always
          command: ["/wave"]
          env:
            - name: DATABASE_URL
              value: "postgres://musicon@musicon.space:5433/musicon"
