name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy repository content to VM
        uses: appleboy/scp-action@master
        with:
          HOST: "82.146.45.164"
          USERNAME: "dmitry"
          PORT: "22"
          PASSWORD: "031201"
          source: "."
          target: ~/AdDoBackendDeploy

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: "82.146.45.164"
          USERNAME: "dmitry"
          PORT: "22"
          PASSWORD: "031201"
          script: ls