name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository content to VM
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "/AdDoBackend"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: 82.146.45.164
          USERNAME: dmitry
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script: ls