version: '3.9'

services:
  service-minio:
    extends:
      file: ../common-services.yml
      service: service-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 3
      timeout: 5s
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.minio"

  create_buckets:
    extends:
      file: ../common-services.yml
      service: create_buckets
    depends_on:
      service-minio:
        condition: service_started

  service-db-redis:
    extends:
      file: ../common-services.yml
      service: service-db-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.redis"

  service-db-postgres:
    extends:
      file: ../common-services.yml
      service: service-db-postgres
    ports:
      - "5432:5432" # redundant
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U musicon" ]
      interval: 10s
      retries: 3
      timeout: 5s
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.postgres"

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"

  common-service-waiter:
    image: alpine
    depends_on:
      service-db-postgres:
        condition: service_healthy
      service-db-redis:
        condition: service_healthy
      service-minio:
        condition: service_started
      create_buckets:
        condition: service_completed_successfully
      consul:
        condition: service_started
    command: "ls"

  user:
    image: registry.musicon.space/user
    deploy:
      replicas: 1
    depends_on:
      common-service-waiter:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    command: "/user"
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.micro.user"
        
  session:
    image: registry.musicon.space/session
    deploy:
      replicas: 1
    depends_on:
      common-service-waiter:
        condition: service_completed_successfully
    command: "/session"
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.micro.session"

  track:
    image: registry.musicon.space/track
    deploy:
      replicas: 1
    depends_on:
      common-service-waiter:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    command: "/track"
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.micro.track"

  album:
    image: registry.musicon.space/album
    deploy:
      replicas: 1
    depends_on:
      common-service-waiter:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    command: "/album"
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.micro.album"

  playlist:
    image: registry.musicon.space/playlist
    deploy:
      replicas: 1
    depends_on:
      common-service-waiter:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    command: "/playlist"
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.micro.playlist"

  artist:
    image: registry.musicon.space/artist
    deploy:
      replicas: 1
    depends_on:
      common-service-waiter:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    command: "/artist"
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.micro.artist"

  images:
    image: registry.musicon.space/images
    deploy:
      replicas: 1
    depends_on:
      common-service-waiter:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    command: "/images"
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.micro.images"

  microservice-waiter:
    image: alpine
    depends_on:
      user:
        condition: service_started
      session:
        condition: service_started
      track:
        condition: service_started
      album:
        condition: service_started
      playlist:
        condition: service_started
      artist:
        condition: service_started
      images:
        condition: service_started

  musicon:
    image: registry.musicon.space/entrypoint
    ports:
      - "8080:8080"
    depends_on:
      common-service-waiter:
        condition: service_completed_successfully
      microservice-waiter:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    command: "/entrypoint"
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        tag: "backend.musicon"

  wait-musicon:
    image: alpine
    depends_on:
      musicon:
        condition: service_started
