---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
  labels:
    app: entrypoint-svc
  namespace: musicon
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: entrypoint
  selector:
    app: entrypoint-svc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: entrypoint-service
#   namespace: musicon
# spec:
#   type: LoadBalancer
#   selector:
#     app: entrypoint-svc
#   ports:
#     - port: 8080 
#       targetPort: 8080
